### ISSUE TITLE
Failure on opening settings while using gnome 3.38

### ISSUE THREAD

**Issue by jhecksonSa** [LGiki/gnome-shell-extension-simple-system-monitor#1]
I use Pop!_os system
[![image](https://user-images.githubusercontent.com/73787010/140791700-98ba2a6c-3b4e-44c7-b98e-c59adac4faa4.png)
](url)

GNOME Shell 3.36.7 exactly

**Comment by LGiki** [comment]
Thanks, this extension is only compatible with GNOME 40 and 41 currently. I will check its compatibility on GNOME 3.3x.
