### ISSUE TITLE
proposal: remove a space between cpu text and value (same with memory usage)

### ISSUE THREAD

**Issue by rszyma** [LGiki/gnome-shell-extension-simple-system-monitor#10]
I'm using this extension to display cpu and memory load. For me the output looks like this:
```
CPU   1% | Mem  70%
```
Now compare this to what I propose to change to instead:
```
CPU  1% | Mem 70%
```
The spaces between texts and values are removed. With 1 space less, spacing looks more natural. Now, the problem with this is lack of spacing when either one of these values hit 100%:
```
CPU100% | Mem100%
```
However, realistically speaking, cpu usage almost never at 100% (unless you're compiling something big). Same holds for memory usage (swap is gonna be used before you hit 100%).

**Comment by LGiki** [comment]
Thank you for your proposal, it is true that CPU and memory usage rarely reaches 100%, except when compiling or running some CPU-intensive tasks, but there may be some users who often encounter 100% usage, I think it would be better to add a switch to control whether to display spaces or not, I will add this feature in the next version soon.

**Comment by LGiki** [comment]
I have just released a new version with a "Show Extra Spaces" switch, enjoy it! :-)
