### ISSUE TITLE
Feature request: add a section for swap memory usage too

### ISSUE THREAD

**Issue by givascu** [LGiki/gnome-shell-extension-simple-system-monitor#12]
It would be nice to have a separate section for Swap Memory, similarly to the "Memory Usage" section (which I'm guessing is just for RAM). This is a common feature of other system monitor extensions as well. The Swap Memory section can be an opt-in feature, i.e. disabled by default.

**Comment by LGiki** [comment]
Thanks, it looks great. I will implement this feature when I have time. Soon or later.

**Comment by givascu** [comment]
The implementation should be fairly straightforward and similar to the current one for RAM (I had a quick glance over the source code in the repo), as the swap memory info is also available in `/proc/meminfo`, e.g.
```
$ cat /proc/meminfo | grep Swap
SwapCached:            0 kB
SwapTotal:      16777212 kB
SwapFree:       16777212 kB
```
Thank you!

**Comment by LGiki** [comment]
Yes, the swap memory info is also included in `/proc/meminfo`. Only a few changes to the code are required. I will implement this feature as soon as possible.

**Comment by LGiki** [comment]
Sorry, I've been busy preparing for my master's thesis and interviews recently, so I haven't had time to implement this feature. But now that I'm done, I've just implemented it and released a new version. If you installed this extension from [extensions.gnome.org](https://extensions.gnome.org/extension/4506/simple-system-monitor/), it will automatically update and take effect the next time you restart. If you installed it manually, please download and install from [the release page](https://github.com/LGiki/gnome-shell-extension-simple-system-monitor/releases/tag/v12). Enjoy it.

**Comment by givascu** [comment]
Thanks, it works! Best of luck!
