### ISSUE TITLE
Arch AUR Update

### ISSUE THREAD

**Issue by MatthieuLeboeuf** [LGiki/gnome-shell-extension-simple-system-monitor#13]
Hello,

Can you update the package on the aur ? (https://aur.archlinux.org/packages/gnome-shell-extension-simple-system-monitor)

Or can you add me as a maintainer ? (https://aur.archlinux.org/account/MatthieuDev)

Thanks

**Comment by LGiki** [comment]
Thank you for the reminder. The package on the aur has been updated, and you have been added as a maintainer.
