### ISSUE TITLE
Please make size static

### ISSUE THREAD

**Issue by sentakuhm** [LGiki/gnome-shell-extension-simple-system-monitor#4]
when values changes the size change with it, can you make size static?!

**Comment by LGiki** [comment]
You can set the font to [monospaced font](https://en.wikipedia.org/wiki/Monospaced_font), e.g. [JetBrains Mono](https://www.jetbrains.com/lp/mono/), [Source Code Pro](http://adobe-fonts.github.io/source-code-pro/), [FiraCode](https://github.com/tonsky/FiraCode), [Hack](https://github.com/source-foundry/Hack), then the size will not change when the value is changed.

As this screenshot shows:
![](https://user-images.githubusercontent.com/20807713/155483262-debd5226-180e-4bc0-9b68-2d5caf4d81ad.gif)
