### ISSUE TITLE
how to always align to left

### ISSUE THREAD

**Issue by sudowanderer** [LGiki/gnome-shell-extension-simple-system-monitor#5]
It is a very nice small tool for gnome. But after reboot, it will align to the right of the bar, if It can be set to left that will be wonderful
! 

![image](https://user-images.githubusercontent.com/21277644/163395424-45dad153-a37b-4da2-b0cc-69313b9fbb10.png)

**Comment by LGiki** [comment]
Thanks for the suggestion, the display position seems to be determined by GNOME, I'll check the documentation later.

**Comment by LGiki** [comment]
The order of elements in the status bar is controlled by GNOME and cannot be controlled by the extension.

One way to adjust the order of extensions is to modify the extension.js file of all installed extensions: [https://askubuntu.com/questions/453969/how-can-i-order-gnome3-shell-extensions-at-the-top/661015#661015](https://askubuntu.com/questions/453969/how-can-i-order-gnome3-shell-extensions-at-the-top/661015#661015).

You can check more details here: [https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/402](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/402).
