### ISSUE TITLE
Add 'Open System Monitor' option

### ISSUE THREAD

**Issue by dominiksalvet** [LGiki/gnome-shell-extension-simple-system-monitor#8]
Hello,
Several times I have found myself trying to open the System Monitor application by clicking the Simple System Monitor stats in the top bar. However, in its menu, there is the Settings item only. For me, it would be handy to have such an option for opening System Monitor directly from the options...

**Comment by LGiki** [comment]
Thanks for your suggestion, I think it's a good idea, I'll add an option to open the System Monitor in the menu soon.

**Comment by LGiki** [comment]
Thanks for your suggestion, I have added an option in the menu for opening the system monitor. The new version has been submitted to [GNOME Extensions](https://extensions.gnome.org/extension/4506/simple-system-monitor/) for review. After approval, the extension will be automatically updated to the latest version and the `Open System Monitor` option will appear in the menu, enjoy it. :-)
