### ISSUE TITLE
It does not work recently

### ISSUE THREAD

**Issue by toantk238** [LGiki/gnome-shell-extension-simple-system-monitor#9]
The extension does not work recently. It shows 0 for both CPU and RAM measurement.

![image](https://user-images.githubusercontent.com/5424557/192591834-7540e4b0-d127-433f-9e24-a22f746d7330.png)

**Comment by LGiki** [comment]
Thanks for reporting this issue.
What is your Linux distribution and Linux kernel version, and can you provide the results of `cat /proc/stat` and `cat /proc/meminfo`?

**Comment by toantk238** [comment]
@LGiki 
I'm using EndeavourOS- a kind of Arch. 
Kernel 5.19.11

`cat /proc/stat`

>cpu  29420 172 8600 254124 1393 633 562 0 0 0
cpu0 2289 7 745 21293 121 111 28 0 0 0
cpu1 2698 66 831 20543 92 87 250 0 0 0
cpu2 2832 8 743 20820 123 33 19 0 0 0
cpu3 2314 13 652 21487 68 31 18 0 0 0
cpu4 2484 7 676 21182 142 36 19 0 0 0
cpu5 2472 13 666 21228 127 34 19 0 0 0
cpu6 2423 14 714 21139 128 109 24 0 0 0
cpu7 2323 8 654 21445 121 33 18 0 0 0
cpu8 2594 7 682 21132 125 32 16 0 0 0
cpu9 2188 5 761 21328 105 57 112 0 0 0
cpu10 2595 6 778 21029 137 32 17 0 0 0
cpu11 2204 12 692 21493 99 31 16 0 0 0
intr 1772231 10 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 5 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 44663 28 28 6899 7243 7973 5531 7753 7273 7091 9690 7707 6721 9361 6254 77 20 1 36 40 56 15 9 2 16 34 60 157119 45 2974 2706 38459 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
ctxt 4132268
btime 1664417703
processes 29698
procs_running 1
procs_blocked 1
softirq 893452 43338 37754 33 157708 70 0 30785 282145 4424 337195



`cat /proc/meminfo`

> MemTotal:       32806200 kB
MemFree:        23786276 kB
MemAvailable:   27829736 kB
Buffers:          269996 kB
Cached:          4244416 kB
SwapCached:            0 kB
Active:          1802472 kB
Inactive:        6318624 kB
Active(anon):      27396 kB
Inactive(anon):  3758096 kB
Active(file):    1775076 kB
Inactive(file):  2560528 kB
Unevictable:          80 kB
Mlocked:              80 kB
SwapTotal:       8388604 kB
SwapFree:        8388604 kB
Zswap:                 0 kB
Zswapped:              0 kB
Dirty:               908 kB
Writeback:             0 kB
AnonPages:       3505340 kB
Mapped:          1439336 kB
Shmem:            178808 kB
KReclaimable:     162160 kB
Slab:             332156 kB
SReclaimable:     162160 kB
SUnreclaim:       169996 kB
KernelStack:       24976 kB
PageTables:        51196 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    24791704 kB
Committed_AS:   16930348 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       70600 kB
VmallocChunk:          0 kB
Percpu:            16320 kB
HardwareCorrupted:     0 kB
AnonHugePages:    935936 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:      4096 kB
FilePmdMapped:      4096 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      773396 kB
DirectMap2M:    11741184 kB
DirectMap1G:    20971520 kB

**Comment by DmitrySkibitsky** [comment]
It also stopped working.

```bash
██████████████████  ████████   dmitry@dmitry-zephyrus 
██████████████████  ████████   ---------------------- 
██████████████████  ████████   OS: Manjaro Linux x86_64 
██████████████████  ████████   Host: Zephyrus M GU502GV_GU502GV 1.0 
████████            ████████   Kernel: 5.19.7-1-MANJARO 
████████  ████████  ████████   Uptime: 50 mins 
████████  ████████  ████████   Packages: 1475 (pacman), 1 (dpkg), 7 (snap) 
████████  ████████  ████████   Shell: zsh 5.9 
████████  ████████  ████████   Resolution: 1920x1080 
████████  ████████  ████████   DE: GNOME 42.4 
████████  ████████  ████████   WM: Mutter 
████████  ████████  ████████   WM Theme: Adwaita 
████████  ████████  ████████   Theme: Adw [GTK2/3] 
████████  ████████  ████████   Icons: Adwaita [GTK2/3] 
                               Terminal: tilix 
                               CPU: Intel i7-9750H (12) @ 4.500GHz 
                               GPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
                               GPU: NVIDIA GeForce RTX 2060 Mobile 
                               Memory: 11508MiB / 15847MiB 

                                                       
                                                       

```

**Comment by LGiki** [comment]
Thanks for providing this information, I will investigate this issue soon. :-)

**Comment by matteoclc** [comment]
I confirm this issue appeared in the last few days on Fedora 36
It shows 0 for network traffic also

thank you!

cat /proc/stat 
cpu  11388 254 4593 278431 1244 883 413 0 0 0
cpu0 1384 30 588 34784 184 113 48 0 0 0
cpu1 1382 37 561 34805 164 164 43 0 0 0
cpu2 1309 36 588 34679 167 218 117 0 0 0
cpu3 1392 32 602 34853 128 77 42 0 0 0
cpu4 1416 22 532 34913 147 74 38 0 0 0
cpu5 1463 35 561 34841 157 80 39 0 0 0
cpu6 1712 33 589 34565 156 76 42 0 0 0
cpu7 1328 25 569 34988 137 77 41 0 0 0
intr 1270367 0 19 0 0 0 0 0 0 0 4732 0 0 137 0 1 0 49 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 728 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 14411 1 0 22 13972 13250 15826 13670 11434 12452 11486 12416 75192 121 124 0 0 0 0 0 0 0 0 0 0 0 0 0 0 49 5265 294 963 559 600 592 615 323 1066 5 2382 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
ctxt 2413404
btime 1664520794
processes 6665
procs_running 1
procs_blocked 0
softirq 721497 76796 84142 12 10514 30 0 8214 240006 0 301783



cat /proc/meminfo 
MemTotal:       16118212 kB
MemFree:         9320112 kB
MemAvailable:   13041348 kB
Buffers:            4176 kB
Cached:          4476072 kB
SwapCached:            0 kB
Active:          1365684 kB
Inactive:        4377980 kB
Active(anon):       5448 kB
Inactive(anon):  1811836 kB
Active(file):    1360236 kB
Inactive(file):  2566144 kB
Unevictable:      518668 kB
Mlocked:            5764 kB
SwapTotal:       8388604 kB
SwapFree:        8388604 kB
Zswap:                 0 kB
Zswapped:              0 kB
Dirty:              1284 kB
Writeback:             0 kB
AnonPages:       1782224 kB
Mapped:           765828 kB
Shmem:            548720 kB
KReclaimable:     105952 kB
Slab:             279608 kB
SReclaimable:     105952 kB
SUnreclaim:       173656 kB
KernelStack:       15600 kB
PageTables:        35512 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    16447708 kB
Committed_AS:    8677684 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       76160 kB
VmallocChunk:          0 kB
Percpu:            11456 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:      367784 kB
DirectMap2M:     9854976 kB
DirectMap1G:     7340032 kB

**Comment by LGiki** [comment]
I have tested on EndeavourOS, Manjaro, Fedora 36 and ArchLinux and this extension works fine, I can' t reproduce this issue.

The `cat /proc/stat` and `cat /proc/meminfo` results you provided seem fine, I need more information to investigate this issue, can you provide the results of `journalctl /usr/bin/gnome-shell -o cat | grep ssm-gnome@lgiki.net -C 5`?

Or reset the plugin settings to default values to see if it works again?

![Screenshot from 2022-09-30 19-37-00](https://user-images.githubusercontent.com/20807713/193262918-61035d8c-2ba8-499c-9e6f-0aefe6eaacec.png)

![Screenshot from 2022-09-29 23-25-32](https://user-images.githubusercontent.com/20807713/193262950-2f69c976-9268-4509-ac89-72db59e1ef22.png)

![temp-2022-09-30-19-55-33](https://user-images.githubusercontent.com/20807713/193264305-e72e6c25-a441-4d7b-8a3d-377bc872fb77.png)

![1](https://user-images.githubusercontent.com/20807713/193263983-bd92af42-f6e5-48f3-a82b-934567488019.png)

**Comment by matteoclc** [comment]
sure:
[gnome-shell.log.gz](https://github.com/LGiki/gnome-shell-extension-simple-system-monitor/files/9683927/gnome-shell.log.gz)

**Comment by LGiki** [comment]
@matteoclc Thanks, this log is useful, can you provide the version of [glib2](https://packages.fedoraproject.org/pkgs/glib2/glib2/), [gjs](https://packages.fedoraproject.org/pkgs/gjs/gjs/) and [gnome-shell](https://packages.fedoraproject.org/pkgs/gnome-shell/gnome-shell/)?

**Comment by matteoclc** [comment]
> @matteoclc Thanks, this log is useful, can you provide the version of [glib2](https://packages.fedoraproject.org/pkgs/glib2/glib2/), [gjs](https://packages.fedoraproject.org/pkgs/gjs/gjs/) and [gnome-shell](https://packages.fedoraproject.org/pkgs/gnome-shell/gnome-shell/)?

glib2-2.72.3-1.fc36.x86_64
glib2-2.72.3-1.fc36.i686
gjs-1.72.2-2.fc36.x86_64
gnome-shell-42.5-1.fc36.x86_64

**Comment by fmonteghetti** [comment]
I started experiencing the same problem.

The issue seems to occur in the instanciation of `Gio.DataInputStream()` in the body of `getCurrentCPUUsage()` and `getCurrentMemoryUsage()`. Perhaps a recent API change?

Here are the errors I get when running the extension:
```
Oct 01 10:41:09 archlaptop gnome-shell[1497]: JS ERROR: TypeError: Object 0x202da072b870 is not a subclass of GObject_Object, it's a Promise
                                              getCurrentCPUUsage@~/.local/share/gnome-shell/extensions/ssm-gnome@lgiki.net/extension.js:135:33
                                              _refresh_monitor@~/.local/share/gnome-shell/extensions/ssm-gnome@lgiki.net/extension.js:407:31
                                              Caused by: Error: This JS object wrapper isn't wrapping a GObject. If this is a custom subclass, are you sure you chained up to the parent _init properly?
Oct 01 10:41:09 archlaptop gnome-shell[1497]: JS WARNING: [resource:///org/gnome/gjs/modules/core/overrides/Gio.js 422]: Too many arguments to method Gio.File.read: expected 1, got 2
Oct 01 10:41:09 archlaptop gnome-shell[1497]: JS ERROR: TypeError: Object 0x202da072c2d8 is not a subclass of GObject_Object, it's a Promise
                                              getCurrentMemoryUsage@~/.local/share/gnome-shell/extensions/ssm-gnome@lgiki.net/extension.js:189:33
                                              _refresh_monitor@~/.local/share/gnome-shell/extensions/ssm-gnome@lgiki.net/extension.js:410:34
                                              Caused by: Error: This JS object wrapper isn't wrapping a GObject. If this is a custom subclass, are you sure you chained up to the parent _init properly?
```
Error obtained with:
```
glib2 2.74.0-2
lib32-glib2 2.74.0-2
gjs 2:1.72.2-1
gnome-shell 1:42.5-1
gnome-shell-extensions 42.3-1
```

**Comment by LGiki** [comment]
I still can't reproduce this issue on my computer, but I changed the API of reading files (replace `Gio.File.read` with [`Gio.File.load_contents`](https://gjs-docs.gnome.org/gio20/gio.file#method-load_contents)), can someone help me to try if this version ([ssm-gnome@lgiki.net.shell-extension.zip](https://github.com/LGiki/gnome-shell-extension-simple-system-monitor/files/9690121/ssm-gnome%40lgiki.net.shell-extension.zip)) will work?

You can install it by:
```bash
gnome-extensions uninstall ssm-gnome@lgiki.net
gnome-extensions install ssm-gnome@lgiki.net.shell-extension.zip
```

**Comment by matteoclc** [comment]
> I still can't reproduce this issue on my computer, but I changed the API of reading files (replace `Gio.File.read` with [`Gio.File.load_contents`](https://gjs-docs.gnome.org/gio20/gio.file#method-load_contents)), can someone help me to try if this version ([ssm-gnome@lgiki.net.shell-extension.zip](https://github.com/LGiki/gnome-shell-extension-simple-system-monitor/files/9690121/ssm-gnome%40lgiki.net.shell-extension.zip)) will work?
> 
> You can install it by:
> 
> ```shell
> gnome-extensions uninstall ssm-gnome@lgiki.net
> gnome-extensions install ssm-gnome@lgiki.net.shell-extension.zip
> ```

it works!!!

![image](https://user-images.githubusercontent.com/40210136/193422405-07017a1f-7924-4878-bc54-7420435442f8.png)

**Comment by JrkNov** [comment]
> > I still can't reproduce this issue on my computer, but I changed the API of reading files (replace `Gio.File.read` with [`Gio.File.load_contents`](https://gjs-docs.gnome.org/gio20/gio.file#method-load_contents)), can someone help me to try if this version ([ssm-gnome@lgiki.net.shell-extension.zip](https://github.com/LGiki/gnome-shell-extension-simple-system-monitor/files/9690121/ssm-gnome%40lgiki.net.shell-extension.zip)) will work?
> > You can install it by:
> > ```shell
> > gnome-extensions uninstall ssm-gnome@lgiki.net
> > gnome-extensions install ssm-gnome@lgiki.net.shell-extension.zip
> > ```
> 
> it works!!!
> 
> ![image](https://user-images.githubusercontent.com/40210136/193422405-07017a1f-7924-4878-bc54-7420435442f8.png)

ssm-gnome@lgiki.net.shell-extension.zip 
Download, unzip, copy to extensions/ssm-gnome@lgiki.net folder and it works perfectly again. Thanks :-)

**Comment by LGiki** [comment]
I just submitted a new version to [Gnome Extensions](https://extensions.gnome.org/extension/4506/simple-system-monitor/), waiting for the system automatically update the extension to the latest version, or manually update it to the latest version and it should work fine, thanks for reporting this issue and providing assistance. :-)

**Comment by matteoclc** [comment]
> I just submitted a new version to [Gnome Extensions](https://extensions.gnome.org/extension/4506/simple-system-monitor/), waiting for the system automatically update the extension to the latest version, or manually update it to the latest version and it should work fine, thanks for reporting this issue and providing assistance. :-)

thank you!

**Comment by toantk238** [comment]
@LGiki Thank you. It works again !
